SystemOrganization addCategory: #'SqueakCheck-Info'!
SystemOrganization addCategory: #'SqueakCheck-Generators'!
SystemOrganization addCategory: #'SqueakCheck-Generators-Tests'!
SystemOrganization addCategory: #'SqueakCheck-SUnit-Tests'!
SystemOrganization addCategory: #'SqueakCheck-SUnit'!
SystemOrganization addCategory: #'SqueakCheck-Runners-Tests'!
SystemOrganization addCategory: #'SqueakCheck-Runners'!
