*SqueakCheck-Integration
pages

	^ #( squeakCheck introduction transcript assignment constants boolean arithmetic
		bitwise conversion block exceptionHandling methodCall conditionalStatement
		iterationStatement character symbol string array orderedCollection
		sortedCollection bag set interval association dictionary internalStream
		fileStream date time point rectangle pen dynamic metaclass debugging
		misc )